services:
  jupyterlab:
    build: .
    restart: always
    tty: true
    expose:
      - "8888"
    ports:
      - "8888:8888"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    env_file:
      - .env
    command: >
      jupyter-lab
      --ip 0.0.0.0
      --allow-root
      --NotebookApp.token=''
      --port=8888
      --notebook-dir=/workspace
      -b localhost
